<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->jQuery(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?>
<style>
  body {
    padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
  }
</style>
<?php echo $this->headLink()->appendStylesheet('/css/bootstrap-responsive.min.css') ?>
<?php echo $this->headTitle(); ?>
</head>
<body>
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">BR-Sandbox</a>
          <div class="nav-collapse">
            <ul class="nav">
				<li class="active"><a href="/">Home</a></li>
				<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown">ACL<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="<?= $this->url(array('module'=> 'acl', 'action' => 'roles'));?>">Role managemnt</a></li>
						
					</ul>
				</li>
            </ul>
			<p class="navbar-text pull-right">
			<?php if($this->LoggedUser()):?>
				Logged in as <a href="<?= $this->url(array('module' => 'user', 'controller' => 'index', 'action'=>'profile'));?>"><?= $this->LoggedUser('name'); ?></a>. <a href="<?= $this->url(array('action' => 'logout', 'controller' => 'index', 'module' => 'user')); ?>">Log out</a> perhaps?
			<?php else: ?>
				<a href="<?= $this->url(array('action' => 'index', 'controller' => 'index', 'module' => 'user')); ?>"><?= $this->translate('Sign in'); ?></a>
			<?php endif; ?>
			</p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
	<?php echo $this->FlashMessenger(); ?>
	<?php echo $this->layout()->content ?>
    </div> <!-- /container -->
</body>
</html>